name: newsify_admin
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.1
  image_picker: ^0.8.4+10
  firebase_storage:
  firebase_core:
  cloud_firestore: ^3.1.10
  flutter_local_notifications: ^9.4.0
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:

    sdk: flutter

flutter:

  uses-material-design: true
